### ISSUE TITLE
Errors after TB upgrade to 102.0b2 (64-bit) Win10

### ISSUE THREAD

**Issue by xsistema** [lieser/dkim_verifier#313] opened 2022-06-04 13:14 UTC
After TB upgrade to 102.0b2 (64-bit) Win10 version, DKIM verifier 4.1.1 no longer working.. Errors:

```
Uncaught Error: Could not find the DkimFavicon element
    get jar:file:///C:/Users/xxx/AppData/Roaming/Thunderbird/Profiles/default/extensions/dkim_verifier@pl.xpi!/experiments/dkimHeader.js:613
    reset jar:file:///C:/Users/xxx/AppData/Roaming/Thunderbird/Profiles/default/extensions/dkim_verifier@pl.xpi!/experiments/dkimHeader.js:840
    onStartHeaders jar:file:///C:/Users/xxx/AppData/Roaming/Thunderbird/Profiles/default/extensions/dkim_verifier@pl.xpi!/experiments/dkimHeader.js:847
    onStartHeaders chrome://messenger/content/msgHdrView.js:506
    processHeaders chrome://messenger/content/msgHdrView.js:558
dkimHeader.js:613:10

expandedFromBox.emailAddresses is undefined dkimHeader.js:690
    _getFromAddress jar:file:///C:/Users/xxx/AppData/Roaming/Thunderbird/Profiles/default/extensions/dkim_verifier@pl.xpi!/experiments/dkimHeader.js:690
    showTooltip jar:file:///C:/Users/xxx/AppData/Roaming/Thunderbird/Profiles/default/extensions/dkim_verifier@pl.xpi!/experiments/dkimHeader.js:731
    showFromTooltip jar:file:///C:/Users/xxx/AppData/Roaming/Thunderbird/Profiles/default/extensions/dkim_verifier@pl.xpi!/experiments/dkimHeader.js:969
    showFromTooltip self-hosted:1115
    result resource://gre/modules/ExtensionParent.jsm:1035
    withCallContextData resource://gre/modules/ExtensionParent.jsm:524
    result resource://gre/modules/ExtensionParent.jsm:1034
    withPendingBrowser resource://gre/modules/ExtensionParent.jsm:534
    result resource://gre/modules/ExtensionParent.jsm:1033
    callAndLog resource://gre/modules/ExtensionParent.jsm:986
    recvAPICall resource://gre/modules/ExtensionParent.jsm:1032
    AsyncFunctionNext self-hosted:632

DKIM_Verifier.AuthVerifier	DEBUG	 AuthResult result found:  {"version":"3.0","dkim":[{"version":"2.0","result":"SUCCESS","sdid":"gmail.com","auid":"@gmail.com","selector":"20210112","warnings":[],"keySecure":false}]} authVerifier.mjs.js:346:6

Could not find the DkimFavicon element dkimHeader.js:613
    get jar:file:///C:/Users/xxx/AppData/Roaming/Thunderbird/Profiles/default/extensions/dkim_verifier@pl.xpi!/experiments/dkimHeader.js:613
    setDkimHeaderResult jar:file:///C:/Users/xxx/AppData/Roaming/Thunderbird/Profiles/default/extensions/dkim_verifier@pl.xpi!/experiments/dkimHeader.js:992
    setDkimHeaderResult self-hosted:1115
    result resource://gre/modules/ExtensionParent.jsm:1035
    withCallContextData resource://gre/modules/ExtensionParent.jsm:524
    result resource://gre/modules/ExtensionParent.jsm:1034
    withPendingBrowser resource://gre/modules/ExtensionParent.jsm:534
    result resource://gre/modules/ExtensionParent.jsm:1033
    callAndLog resource://gre/modules/ExtensionParent.jsm:986
    recvAPICall resource://gre/modules/ExtensionParent.jsm:1032
    AsyncFunctionNext self-hosted:632

DKIM_Verifier.background	FATAL	 Unexpected error during verifyMessage <unavailable> background.mjs.js:142:7
    verifyMessage moz-extension://de74144d-d2f9-4200-ab3a-2f2f0882710e/content/background.mjs.js:142

Could not find the DkimFavicon element dkimHeader.js:613
    get jar:file:///C:/Users/xxx/AppData/Roaming/Thunderbird/Profiles/default/extensions/dkim_verifier@pl.xpi!/experiments/dkimHeader.js:613
    setDkimHeaderResult jar:file:///C:/Users/xxx/AppData/Roaming/Thunderbird/Profiles/default/extensions/dkim_verifier@pl.xpi!/experiments/dkimHeader.js:992
    setDkimHeaderResult self-hosted:1115
    result resource://gre/modules/ExtensionParent.jsm:1035
    withCallContextData resource://gre/modules/ExtensionParent.jsm:524
    result resource://gre/modules/ExtensionParent.jsm:1034
    withPendingBrowser resource://gre/modules/ExtensionParent.jsm:534
    result resource://gre/modules/ExtensionParent.jsm:1033
    callAndLog resource://gre/modules/ExtensionParent.jsm:986
    recvAPICall resource://gre/modules/ExtensionParent.jsm:1032
    AsyncFunctionNext self-hosted:632
```

**Comment by lieser** [comment] 2022-06-04 13:52
This is probably a duplicate of #306.

Please try the version attached to https://github.com/lieser/dkim_verifier/issues/312#issuecomment-1141493203.

**Comment by xsistema** [comment] 2022-06-04 14:23
Yes, indeed, new version is working, just that a few pixel (7px) padding below and 2px above displayed line would be nice:
`<div id="expandedDkim-verifierRow" class="message-header-row" style="margin-top:3px; margin-bottom:7px">`

**Comment by lieser** [comment] 2022-06-12 12:47
Fixed the spacing to the bottom by moving there exactly the row is added.

The spacing to the row above is still the same (6px), and also the value between Thunderbird's own rows. The reason why the spacing seems to be wrong then looking at the row names on the left is because not all rows have the same hight. E.g. the subject and DKIM row are 16px height, but the to row is 20px height.

**Closed by lieser** 2022-06-12 12:47 UTC
Labels: bug, duplicate, compatibility
