### ISSUE TITLE
Internal error on emails from spothero.com

### ISSUE THREAD

**Issue by Pascal666** [lieser/dkim_verifier#321] opened 2022-07-22 21:05 UTC
v5.1.0 on TB 91.11.0 (64-bit)

DKIM_Verifier.Verifier	FATAL	 <unavailable> verifier.mjs.js:1335:8
    _handleException moz-extension://c59aead9-8e8f-4b9a-827f-4513ce0adfbe/modules/dkim/verifier.mjs.js:1335
    _processSignatures moz-extension://c59aead9-8e8f-4b9a-827f-4513ce0adfbe/modules/dkim/verifier.mjs.js:1378

**Comment by lieser** [comment] 2022-07-23 10:35
Thanks for the report. Unfortunately the error message does not provide enough information to see what is going wrong.

Could you please send me an affected email as a saved eml file via email (lieser+dkim@posteo.net)?

**Comment by lieser** [comment] 2022-07-23 16:03
Thanks for sending me the example mail.

The problem is the empty `Reply-To: ` header. Will have a look if that is valid.
But regardless of that, how the add-on handles an invalid Reply-To header needs to be improved.

A workaround would be staying with the 5.0.0 version for now, as the Reply-To header is only read as part of the new warning about unsigned headers.

The reason for the incomplete error message is that how Thunderbird shows log messages of add-ons in the error console is broken. Using the debugging view of the add-on shown a more useful message. Will update the wiki about this problem.

**Comment by lieser** [comment] 2022-08-15 17:16
This should be now fixed in the 5.1.1 version.

**Closed by lieser** 2022-08-15 17:16 UTC
Labels: bug
