### ISSUE TITLE
Add option to select multiple and/or all DKIM keys in store

### ISSUE THREAD

**Issue by agowa** [lieser/dkim_verifier#433] opened 2024-02-10 18:15 UTC
Hi, could you please add an option to select multiple keys in the DKIM keys store and/or the option to clear all?

I've tried to disable the store, restart Thunderbird, and re-enable it. However it did preserve the keys instead of forgetting about them. Therefore I'd like to request adding an option to clear all of the keys currently in the DKIM keys store. (General > Verify DKIM signatures > DKIM keys...)

Also the view currently has a button "Delete selected keys", however it is only possible to select one at a time and trying to select more results in only one of them actually being deleted. As well as trying to select them currently results in only being able to select multiple cells or as text. Similar the option "Select all" within the right click context menu will select the entire table as if it was text and it also doesn't work with the "Delete selected keys" button to clear the list.

**Comment by lieser** [comment] 2024-02-10 19:29
The table view was already changed to allow deleting multiple entries.

You could already try out the version I posted in 
https://github.com/lieser/dkim_verifier/issues/305#issuecomment-1881948632, or pack the latest matter version yourself.

Closing as a duplicate of https://github.com/lieser/dkim_verifier/issues/305.

**Closed by lieser** 2024-02-10 19:29 UTC
