### ISSUE TITLE
DKIM verification fail with DNS error

### ISSUE THREAD

**Issue by consultingroup** [lieser/dkim_verifier#133] opened 2018-11-29 07:54 UTC
I get a DNS error in the DKIM verification.

Sample sent via mail to you.

**Comment by consultingroup** [comment] 2018-12-03 16:08
@lieser: Hi, any news for this?

**Comment by lieser** [comment] 2018-12-03 21:01
The Error I get with the E-Mail you send me is `Invalid (No DKIM key found in DNS server)`.

The signature claims to be from gmail.com, signed with the key `dkim._domainkey.gmail.com`.
The problem is that the DKIM key for the signature does not exist.

Another weird think is, that the `Received` headers inside the e-mail do not contain anything from gmail/google. I doubt gmail would sign any e-mail not send through their servers.

For me the whole e-mails locks like spam, with a bad attempt to let it look more realistic by adding a fake DKIM signature.

**Comment by consultingroup** [comment] 2018-12-04 07:37
Yes, the mail I have received is most likely spam.

It would be nice if the plug-in detect this and give a more clear indication, with the current indication it seems only a temporary DNS problem.

**Comment by lieser** [comment] 2019-01-13 18:30
As I do not see a reliable and easy way to distinguish between DNS misconfiguration and spam, I will close this.

If someone has an idea let me know.

**Closed by lieser** 2019-01-13 18:30 UTC
