### ISSUE TITLE
Can multiple DKIM keys producing an "internal error"? (possible example enclosed) 

### ISSUE THREAD

**Issue by fommio** [lieser/dkim_verifier#276] opened 2021-09-08 18:39 UTC
Hey,

enclosed the header of the affected mail (it's a newsletter).

Is it because of the two DKIM keys?

[header.txt](https://github.com/lieser/dkim_verifier/files/7131078/header.txt)

![{2021-09-08}__{08-30-52PM}](https://user-images.githubusercontent.com/67462955/132565983-2b677210-d421-447b-8541-793d0c5e676e.png)

**Comment by lieser** [comment] 2021-09-08 21:22
Thanks a lot for reporting the issue.

> Is it because of the two DKIM keys?

Do you mean the two `DKIM-Signature` headers in the mail (Note that this are not the DKIM keys)?
No, this should not cause any problems.

Could you please post or send me the log output, best with debug enabled in the advanced options? https://github.com/lieser/dkim_verifier/wiki/Debug#view-error-and-debug-messages

If you can reliably reproduce the error with that mail, it would also be helpful if you could send me the unmodified mail to lieser+dkim@posteo.net.

**Comment by fommio** [comment] 2021-09-09 11:35
> Thanks a lot for reporting the issue.
> 
> > Is it because of the two DKIM keys?
> 
> Do you mean the two `DKIM-Signature` headers in the mail (Note that this are not the DKIM keys)?
> No, this should not cause any problems.
> 
> Could you please post or send me the log output, best with debug enabled in the advanced options? https://github.com/lieser/dkim_verifier/wiki/Debug#view-error-and-debug-messages
> 
> If you can reliably reproduce the error with that mail, it would also be helpful if you could send me the unmodified mail to [lieser+dkim@posteo.net](mailto:lieser+dkim@posteo.net).

Here is the log (with debug enabled) - this is the instant content which is produced as soon as I click on the mail:

[console-export-2021-9-9_13-22-20.txt](https://github.com/lieser/dkim_verifier/files/7136137/console-export-2021-9-9_13-22-20.txt)

I have just emailed you the original email.

**Comment by fommio** [comment] 2021-09-09 11:46
I found a mail from 2019 in my gmail inbox as a reference: Gmail doesn't show any problems here. If I import the 2019 mail into Thunderbird, the error can be reproduced:

![{2021-09-09}__{01-44-02PM}](https://user-images.githubusercontent.com/67462955/132680078-58bd667e-b43a-4c2b-a667-f3ad17adae54.png)
![{2021-09-09}__{01-45-10PM}](https://user-images.githubusercontent.com/67462955/132680093-baa421f4-7824-4a00-962e-e86e7ab189ab.png)

**Comment by fommio** [comment] 2021-09-09 11:54
By the way, i am using Thunderbird 91.1.0

**Comment by lieser** [comment] 2021-09-10 22:31
Sry, forgot that I had an unreleased version of the addon installed, which was the reason I could not reproduce the issue.

The problem is an invalid List-ID and a duplicate of #262. The next version will silently ignore this error.
Note that the last example you send, and which works in 4.0.0, also contains an invalid List-ID. Because of another error in 4.0.0 with the parsing of the List-ID, this is however not detected, and therefore not causing an internal error.

**Closed by lieser** 2021-09-10 22:31 UTC
Labels: bug
