### ISSUE TITLE
Thunderbird 133 - Not compatible

### ISSUE THREAD

**Issue by JohnPlanetary** [lieser/dkim_verifier#474] opened 2024-12-04 19:42 UTC
It would be nice to make the necessary changes to make it compatible with the latest Mozilla Thunderbird 133 version, since currently the latest version v5.4.0 of DKIM Verifier is not compatible and is not usable in the Thunderbird.

**Comment by lieser** [comment] 2024-12-19 23:26
Thanks a lot for reporting and sry for the late response. This is a duplicate of #470.

As I wrote where I just marked the latest version of the addon as compatible with up to Thunderbird 135.

**Closed by lieser** 2024-12-19 23:26 UTC

**Comment by JohnPlanetary** [comment] 2024-12-21 23:02
Thanks.
I confirmed, it works again.
