### ISSUE TITLE
Variable browser.dkimheader undefined.

### ISSUE THREAD

**Issue by egberts** [lieser/dkim_verifier#260] opened 2021-05-13 00:25 UTC
Thunderbird 78.10.1
dkim_verifier 4.0.0
No other Add-On plugins.

After removing the private browser settings (issue #259, that is normally found in Firefox) from the Thunderbird config editor, and restarting the Thunderbird executable process, 

I get an undefined reference to `browser.dkimheader`.

:-(

```
DKIM_Verifier.background	FATAL	 Unexpected error during onMessageDisplayed TypeError: browser.migration is undefined
    migratePrefs moz-extension://263d55c8-e272-1645-bd5e-42512c5e1dfa/modules/migration.mjs.js:36
background.mjs.js:173:7
    <anonymous> moz-extension://263d55c8-e272-1645-bd5e-42512c5e1dfa/content/background.mjs.js:173
TypeError: browser.dkimHeader is undefined background.mjs.js:174:3
DKIM_Verifier.background	FATAL	 Unexpected error during onMessageDisplayed TypeError: browser.migration is undefined
    migratePrefs moz-extension://263d55c8-e272-1645-bd5e-42512c5e1dfa/modules/migration.mjs.js:36
background.mjs.js:173:7
    <anonymous> moz-extension://263d55c8-e272-1645-bd5e-42512c5e1dfa/content/background.mjs.js:173
TypeError: browser.dkimHeader is undefined background.mjs.js:174:3
DKIM_Verifier.background	FATAL	 Unexpected error during onMessageDisplayed TypeError: browser.migration is undefined
    migratePrefs moz-extension://263d55c8-e272-1645-bd5e-42512c5e1dfa/modules/migration.mjs.js:36
background.mjs.js:173:7
    <anonymous> moz-extension://263d55c8-e272-1645-bd5e-42512c5e1dfa/content/background.mjs.js:173
TypeError: browser.dkimHeader is undefined background.mjs.js:174:3
```

**Comment by lieser** [comment] 2021-05-13 10:30
The add-on contains so called experiments to do some privileged things (see also https://github.com/lieser/dkim_verifier/wiki/FAQ#why-does-the-add-on-need-full-unrestricted-access-to-thunderbird).
For an unknown reason they do not seem to be initialized correctly by Thunderbird.

Can you please try:
1. Removing the add-on
2. Restart Thunderbird (if one time does not help, please also try it with two restart, even if I think it will not make a difference)
3. Add the add-on again

This should result in Thunderbird deleting any data of the add-on, hopefully getting it in a working state again.

Please also check if you may have missed any other error shown before the one you posted, that could be related.

**Comment by lieser** [comment] 2021-07-03 23:41
Closing this for now, as I could not reproduce the problem.
Please let me know and reopen the issue if you still have this problem.

**Closed by lieser** 2021-07-03 23:41 UTC
