### ISSUE TITLE
Revalidation DNS - v4.0.0pre1

### ISSUE THREAD

**Issue by alexetgus** [lieser/dkim_verifier#212] opened 2020-09-08 10:12 UTC
In the event of a DNS problem, which is frequent with a Java-Script DNS script, it is not possible to try to revalidate as was the case with version 68 of TH.

Even worse! The answer seems to be memorised and it is all the results of the mails which are in error...
**Example :** The DKIM google.com test returns an error. All the emails received by Google will be marked "in error"...
No more tests will be possible.

**TH :** 78.2.1 - **Plugin :** 4.0.0pre1

![dkim_plugin-google](https://user-images.githubusercontent.com/6213199/92464146-0a342280-f1cd-11ea-85c5-ce9189be18b6.png)

**Comment by lieser** [comment] 2020-09-16 17:51
> In the event of a DNS problem, which is frequent with a Java-Script DNS script, it is not possible to try to revalidate as was the case with version 68 of TH.

Have you tied disabling getting the DNS servers from the OS? maybe this is causing problems.

> Even worse! The answer seems to be memorised

This should not be the case, as it is not yet implemented. What you are maybe observing is that all configured DNS servers there not reachable, which means they will not be retried until TB restarts or the DNS settings change.

Could you please enable debugging in the advanced add-on options, and post the output here or send it to me via email?
See also https://github.com/lieser/dkim_verifier/wiki/Debug

**Comment by alexetgus** [comment] 2020-09-16 18:26
This seems to be working again since a restart of TB.

My concerned system is Win7 with a local DNS server (Bind). Windows DNS service are disabled.
I will do a debug if it happens again.

**Comment by lieser** [comment] 2020-10-05 19:31
I will close the issue for now, as I assume you there not able to reproduce the problem.

If you encounter the problem again, please reopen this issue with more information.

**Closed by lieser** 2020-10-05 19:31 UTC
