### ISSUE TITLE
[bug] Exception in libunboundWorker - libunbound not correctly initialized (ub_resolve missing)

### ISSUE THREAD

**Issue by n8v8R** [lieser/dkim_verifier#179] opened 2019-09-23 06:51 UTC
* W10 Pro x_64 v1903 b18362.356
* TB 70.0b2 (64-bit)
* DKIM_V 3.0.1
____
Setting

![Annotation 2019-09-23 084714](https://user-images.githubusercontent.com/13611490/65406114-c4752300-ddde-11e9-95f7-d28c94486c7d.png)

The file (libunbound-8.dll) is in residence at the specified path

![Annotation 2019-09-23 085801](https://user-images.githubusercontent.com/13611490/65406620-54679c80-dde0-11e9-8d16-3d2025a47590.png)

however the console evidently displays

> DKIM_Verifier.libunbound	DEBUG	libunboundWorker: Posting exception back to main script: Error: couldn't open library D:\apps\email\tb\libunbound\libunbound-8.dll: error 126
> libunbound.jsm:297

> 
> DKIM_Verifier.libunbound	FATAL	Exception in libunboundWorker: DKIM verifier internal error (DKIM_DNSERROR_UNKNOWN): libunboundWorker: Error: couldn't open library D:\apps\email\tb\libunbound\libunbound-8.dll: error 126(resource://dkim_verifier/helper.jsm:430:3) JS Stack trace: libunboundWorker.onmessage@libunbound.jsm:316:16
> EventHandlerNonNull*@libunbound.jsm:271:1
> DNS_resolve@DNSWrapper.jsm:92:15
> getDMARCRecord@dkimDMARC.jsm:264:25
> getDMARCPolicy@dkimDMARC.jsm:181:22
> Policy_shouldBeSigned@dkimDMARC.jsm:93:24
> Policy_shouldBeSigned/promise<@dkimPolicy.jsm:348:32
> async*Policy_shouldBeSigned@dkimPolicy.jsm:360:5
> Verifier_createMsg/promise<@dkimVerifier.jsm:1478:38
> async*Verifier_createMsg@dkimVerifier.jsm:1481:5
> _authVerifier_verify/promise<@AuthVerifier.jsm:129:34
> _authVerifier_verify@AuthVerifier.jsm:187:5
> Display_onEndHeaders/promise<@dkim.js:970:54
> Display_onEndHeaders@dkim.js:978:5
> onEndHeaders@msgHdrView.js:480:32
> processHeaders@msgHdrView.js:608:10
> libunbound.jsm:322

**Comment by n8v8R** [comment] 2019-09-23 08:10
After having reduced the library files reduced to

![Annotation 2019-09-23 100445](https://user-images.githubusercontent.com/13611490/65410046-a4972c80-dde9-11e9-81ca-ee329edc6743.png)

and settings

![Annotation 2019-09-23 100445](https://user-images.githubusercontent.com/13611490/65410282-3acb5280-ddea-11e9-8250-f0d4720fe80b.png)

the _error 126_ is not exhibited any more but instead the console now prints

> DKIM_Verifier.libunbound	DEBUG	libunboundWorker: Posting exception back to main script: Error: libunbound not correctly initialized (ub_resolve missing)

> DKIM_Verifier.Verifier	ERROR	DKIM verifier internal error (DKIM_DNSERROR_UNKNOWN): libunboundWorker: Error: libunbound not correctly initialized (ub_resolve missing)(resource://dkim_verifier/helper.jsm:430:3) JS Stack trace: libunboundWorker.onmessage@libunbound.jsm:316:16
> EventHandlerNonNull*@libunbound.jsm:271:1
> DNS_resolve@DNSWrapper.jsm:92:15
> getDMARCRecord@dkimDMARC.jsm:264:25
> getDMARCPolicy@dkimDMARC.jsm:181:22
> Policy_shouldBeSigned@dkimDMARC.jsm:93:24
> Policy_shouldBeSigned/promise<@dkimPolicy.jsm:348:32
> async*Policy_shouldBeSigned@dkimPolicy.jsm:360:5
> Verifier_createMsg/promise<@dkimVerifier.jsm:1478:38
> async*Verifier_createMsg@dkimVerifier.jsm:1481:5
> _authVerifier_verify/promise<@AuthVerifier.jsm:129:34
> _authVerifier_verify@AuthVerifier.jsm:187:5
> Display_onEndHeaders/promise<@dkim.js:970:54
> Display_onEndHeaders@dkim.js:978:5
> onEndHeaders@msgHdrView.js:480:32
> processHeaders@msgHdrView.js:608:10
> libunbound.jsm:316:16
>     onmessage resource://dkim_verifier/libunbound.jsm:316
>     EventHandlerNonNull* resource://dkim_verifier/libunbound.jsm:271
>     DNS_resolve resource://dkim_verifier/DNSWrapper.jsm:92
>     getDMARCRecord resource://dkim_verifier/dkimDMARC.jsm:264
>     getDMARCPolicy resource://dkim_verifier/dkimDMARC.jsm:181
>     Policy_shouldBeSigned resource://dkim_verifier/dkimDMARC.jsm:93
>     promise resource://dkim_verifier/dkimPolicy.jsm:348
>     Policy_shouldBeSigned resource://dkim_verifier/dkimPolicy.jsm:360
>     promise resource://dkim_verifier/dkimVerifier.jsm:1478
>     Verifier_createMsg resource://dkim_verifier/dkimVerifier.jsm:1481
>     promise resource://dkim_verifier/AuthVerifier.jsm:129
>     _authVerifier_verify resource://dkim_verifier/AuthVerifier.jsm:187
>     promise chrome://dkim_verifier/content/dkim.js:970
>     Display_onEndHeaders chrome://dkim_verifier/content/dkim.js:978
>     onEndHeaders chrome://messenger/content/msgHdrView.js:480
>     processHeaders chrome://messenger/content/msgHdrView.js:608

**Comment by lieser** [comment] 2019-09-23 23:11
Please have a lock at https://github.com/lieser/dkim_verifier/issues/170#issuecomment-534318043, and see if that helps.

Also note that I will close this issue, as it seems to be a duplicate of #170 

As for not seeing the `Error: couldn't open library D:\apps\email\tb\libunbound\libunbound-8.dll: error 126` error again:
This only happens if the add-on actually tries to load the library. If it fails, it will **not** be tried again automatically. Change the path setting for libunbound, or better simply restart TB to trigger a reload.

**Closed by lieser** 2019-09-23 23:11 UTC
