### ISSUE TITLE
Internal Error probably due to specific type of encoding

### ISSUE THREAD

**Issue by gitflo** [lieser/dkim_verifier#235] opened 2021-01-12 15:27 UTC
Hi there,

only "Interner Fehler" (internal error) is displayed on mails from a specific sender.

My first guess was that it's an issue due to German Umlaut characters, but that doesn't seem to be the case.

Mails with the following From are treated correctly:  `From: =?UTF-8?B?RmzDtnJpw6RuIEhvbGVjemVr?= <xy@some-where.de>`
Mails with the following From lead to the error:  `From: =?utf-8?Q?Dr._Heinz_M=C3=A4rck?= <abc@foo-bar.de>`

Here's the related content from Thunderbird's error console:

`DKIM_Verifier.background	FATAL	 Unexpected error during onMessageDisplayed Error: From header does not contain an address`
`    parseFromHeader moz-extension://2e35920c-0eb9-44ff-b12d-7dd6b4c71581/modules/msgParser.mjs.js:165`
`    verify moz-extension://2e35920c-0eb9-44ff-b12d-7dd6b4c71581/modules/AuthVerifier.mjs.js:122`
`    <anonym> moz-extension://2e35920c-0eb9-44ff-b12d-7dd6b4c71581/content/background.mjs.js:164`
`background.mjs.js:164:7`

Environment:
Thunderbird 78.6.0 (32-Bit)
DKIM Verifier 4.0.0pre4

Kind regards
 Florian

**Comment by lieser** [comment] 2021-01-13 18:42
Thanks a lot for reporting. The problem is the dot in `Dr.`.

From my understanding this is only valid in the [Obsolete Syntax](https://tools.ietf.org/html/rfc5322#section-4), which I left out in the parsing I needed to add during the porting to TB 78.
As this should no longer be used, I hoped I could just left it out to simplify the code.

Will try to fix this in the next release.

**Comment by lieser** [comment] 2021-02-07 13:56
This should be fixed now, you can get a test version at https://github.com/lieser/dkim_verifier/issues/199#issuecomment-774676192.

Please reopen the issue if it is still not working for you.

**Closed by lieser** 2021-02-07 13:56 UTC
Labels: bug

**Comment by gitflo** [comment] 2021-02-08 08:59
Just been testing it. The version in dkim_verifier-4.0.0pre4.1.zip fixed this issue, great, thanks!
